/* Generated by tools/export_curriculum_pilot.js from ordered lesson/card IDs only. */
(function(root){
  'use strict';
  root.CQ_CURRICULUM_PILOT={
  "lessons": [
    {
      "id": "L_pilot_service",
      "name": "Service: Summons and Subpoena",
      "cover": "default",
      "cards": [
        "summons",
        "svs"
      ],
      "blurb": "Read the source-backed rules for summonses, service, appearances, and subpoenas."
    }
  ],
  "sourceBackedCardIds": [
    "summons",
    "svs"
  ]
};
})(typeof window !== 'undefined' ? window : globalThis);
